name: amplicon-wf-tutorial
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bash_kernel
  - coreutils
  - r-irkernel
  - r-base
  - r-tidyverse
  - r-vegan
  - r-dendextend
  - bioconductor-dada2
  - bioconductor-decipher
  - bioconductor-phyloseq
  - bioconductor-deseq2
  - fastqc
  - multiqc
