name: amplicon-wf-tutorial
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bash_kernel=0.9.0
  - coreutils=9.1
  - r-irkernel=1.3.2
  - r-base=4.1.3
  - r-tidyverse=1.3.2
  - r-vegan=2.6_4
  - bioconductor-dada2=1.22.0
  - bioconductor-decipher=2.22.0
  - bioconductor-phyloseq=1.38.0
  - bioconductor-deseq2=1.34.0
  - fastqc=0.11.9
  - multiqc=1.12
